baseURL = "https://dylangore.github.io/dylangore.ie/"
languageCode = "en-ie"
title = "Dylan Gore"
theme = "dylangore"
googleAnalytics = ""

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# [[menu.main]]
#     url = "/posts/"
#     name = "Posts"
#     weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@hello@dylangore.ie"
    name = "envelope-o"
    weight = 1
    pre = "fa-solid"

[[menu.icon]]
    url = "https://github.com/DylanGore/"
    name = "github"
    weight = 2
    pre = "fa-brands"

[[menu.icon]]
    url = "https://twitter.com/DylanGore/"
    name = "twitter"
    weight = 3
    pre = "fa-brands"

[[menu.icon]]
   url = "https://dev.to/DylanGore/"
   name = "dev"
   weight = 4
   pre = "fa-brands"

[[menu.icon]]
    url = "https://www.linkedin.com/in/dylangore/"
    name = "linkedin-in"
    weight = 5
    pre = "fa-brands"
