baseURL = "https://dylangore.github.io/dylangore.ie/"
languageCode = "en-ie"
title = "Dylan Gore"
theme = "dylangore"
googleAnalytics = ""

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 2

# [[menu.main]]
#     url = "/posts/"
#     name = "Posts"
#     weight = 2

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4