baseURL = "https://dylangore.github.io/dylangore.ie/"
languageCode = "en-ie"
title = "Dylan Gore"
theme = "dylangore"
googleAnalytics = ""
enableEmoji = true
# [[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1

# [[menu.main]]
#     url = "/projects/"
#     name = "Projects"
#     weight = 2

# [[menu.main]]
#     url = "/posts/"
#     name = "Posts"
#     weight = 2

# [[menu.main]]
#     url = "/contact/"
#     name = "Contact"
#     weight = 4

[sitemap]
  filename = "sitemap.xml"

# Assets
[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "./assets/sass/bootstrap"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js"
    target = "./assets/js/bootstrap"