baseURL = "https://dylangore.github.io/dylangore.ie/"
languageCode = "en-ie"
title = "Dylan Gore"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Dylan Gore"
    description = "Personal portfolio and blog."
    githubUsername = "dylangore"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# [[menu.main]]
#     url = "/about/"
#     name = "About"
#     weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@hello@dylangore.ie"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/DylanGore/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/DylanGore/"
    name = "twitter"
    weight = 3

#[[menu.icon]]
#    url = "https://dev.to/DylanGore/"
#    name = "dev"
#    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/dylangore/"
    name = "linkedin"
    weight = 5
